# Currently not available
download:
	wget -c --waitretry=5 http://www.omegawiki.org/downloads/omegawiki-lexical.sql.gz

# Memo
upload:
	huggingface-cli upload --repo-type=dataset n7shi/OmegaWiki $(FILENAME)
